apiVersion: apps/v1
kind: Deployment
metadata:
  name: wos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wos
  template:
    metadata:
      labels:
        app: wos
    spec:
      containers:
      - image: okteto.dev/wos:latest
        name: wos
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "8a534699-75ec-46f3-9917-7ee1f7be20c0"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "8a534699-75ec-46f3-9917-7ee1f7be20c0"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
